---
output: stevetemplates::cv
geometry: margin=0.5in

title: "Resume"
author: Ariel Mundo

jobtitle: "Graduate Research Assistant"
address: "Department of Biomedical Engineering · University of Arkansas · Fayetteville, AR"
fontawesome: yes
email: aimundo@uark.edu
github: aimundo
# twitter: stevenvmiller
#osf: "Enter 5 digit osf string here"
phone: "+1 479 800 8714"
web: aimundo.rbind.io
updated: yes

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
linkcolor: blue
urlcolor: blue
---

# Education

*University of Arkansas*, PhD. Biomedical Engineering \hfill Expected May 2022

*Universidad Rafael Landivar (Guatemala)*, B.S. Chemical Engineering (_cum laude_) \hfill 2009


# Research Experience

**University of Arkansas**

_Graduate Research Assistant_ (University of Arkansas, Fayetteville, AR) \hfill 2017-Present

- Design and execute experiments in a murine model of colon cancer using optics (spectroscopy), molecular biology (qPCR), and imaging to longitudinally quantify changes in perfusion and angiogenesis in response to chemotherapy.

- Implement Statistical semi-parametric models (generalized additive models) to analyze longitudinal data.

# Other Relevant Experience

**Universidad Rafael Landivar**

_Teaching Assistant Professor_  \hfill 2016-2017

- Professor of Chemistry at the Environmental and Agricultural Sciences Department
- Prepared lectures, supervised labs, mentored students, wrote lab manuals

_Adjunct Professor_ \hfill 2013-2017

- Taught Introductory Chemistry in the Engineering, Environmental and Agricultural, and Health Sciences Departments

**Lacteos Balcanicos Glad**

_Assistant Plant Engineer_ \hfill 2012

- In charge of the production of the main product (yogurt, $\approx$ 3000 L per week). Responsible for raw material inventory, personnel management, and complete production cycle.

# Publications
## Journal Articles

**Mundo, Ariel I.**, Muldoon, Timothy J. "Longitudinal examination of perfusion and angiogenesis markers in primary colorectal tumors shows distinct signatures for metronomic and maximum-tolerated dose strategies". 
(preprint available in _bioRxiv_, under revision). https://doi.org/10.1101/2022.02.07.479423   

**Mundo, Ariel I.**, Tipton, John R., Muldoon, Timothy J.. "Generalized additive models to analyze non-linear trends in biomedical longitudinal data using R: Beyond repeated measures ANOVA and Linear Mixed Models." (preprint available in _bioRxiv_, under revision). https://doi.org/10.1101/2021.06.10.447970

**Mundo, Ariel I.**, Greening, Gage, Fahr, Michael J., Hale, Lawrence N., Bullard, Elizabeth, Rajaram, Narasimhan,, and Muldoon, Timothy J. "Diffuse reflectance spectroscopy to monitor murine colorectal tumor progression and therapeutic response." _Journal of Biomedical Optics_ (2020). https://doi.org/10.1117/1.JBO.25.3.035002

Greening, Gage, **Mundo, Ariel I.**, Rajaram, Narasimhan, Muldoon, Timothy J. "Sampling depth of a diffuse reflectance spectroscopy probe for _in-vivo_ physiological quantification of murine subcutaneous tumor allografts". _Journal of Biomedical Optics_ (2018). https://doi.org/10.1117/1.JBO.23.8.085006


## Conference Presentations

**Mundo, Ariel I.**, Muldoon, Timothy J. "Longitudinal optical and molecular quantification provides insight into the effect of different dosing strategies in colorectal cancer" _Accepted_. 2022 Biophotonics Congress: Biomedical Optics, Fort Lauderdale, FL, USA, April 2022.

**Mundo, Ariel I.** "Statistics and Reproducibility in Biomedical Research: Why we need both". Toronto Workshop on Reproducibility, University of Toronto, February 2022. Recording available [here](https://www.youtube.com/watch?v=Fvkp20X5xwA).

**Mundo, Ariel I.** "Using generalized additive models for biomedical longitudinal data. _When linear models don't work_". RMedicine 2021 Conference. Recording: https://tinyurl.com/39epnrp6 Repository (slides and data): https://aimundo.rbind.io/talks/gams-biomedical/

**Mundo, Ariel I.**, Muhammad, Abdussaboor, and Muldoon, Timothy J. "Optical and molecular longitudinal tracking of primary colorectal murine tumors shows differences in the angiogenic response to maximum-tolerated and metronomic approaches." In Label-free Biomedical Imaging and Sensing (LBIS) 2021, vol. 11655, p. 116551C. _International Society for Optics and Photonics_, 2021. https://doi.org/10.1117/12.2576906

**Mundo, Ariel I.**, Bullard, Elizabeth, Quinn, Kyle P., and Muldoon, Timothy J. "Optical spectroscopic and imaging biomarkers of ulcerative colitis disease progression and remission (Conference Presentation)." In Multiscale Imaging and Spectroscopy, vol. 11216, p. 1121605. _International Society for Optics and Photonics_, 2020. https://doi.org/10.1117/12.2543369

**Mundo, Ariel I.**, Greening, Gage, and Muldoon, Timothy J. "Characterization of a multimodal endoscopically deployable veterinary spectroscopy and imaging probe to determine therapeutic response in a murine orthotopic tumor model." In Label-free Biomedical Imaging and Sensing (LBIS) 2019, vol. 10890, p. 108901L. _International Society for Optics and Photonics_, 2019.


# Awards and Recognition

_Professional Awareness, Advancement, and Development (PADD) Scholar_ \hfill 2020-2021
 
 Received funding and participated in the PAAD program to supplement my graduate education in persuasive speaking, commercialization, and data science.
 
 _OMNI Endowed International Scholarship_ \hfill 2020

Granted as a scholar fulfilling the mission of the OMNI Center in Fayetteville

_Fulbright Faculty Development Scholarship_ \hfill 2017-2019

Only two scholarships awarded for that period in the whole country

# Grants

_Arkansas Biosciences Institute 2021 seed grant competition _ \hfill 2021

Main author on a proposal submitted with Dr. Timothy J. Muldoon from the Department of Biomedical Engineering to examine gene expression and optically derived markers in a mouse model of colorectal cancer ($30,000 in funding). _Proposal scored in the top 2 of all the individual research projects for the cycle_.
