---
output: stevetemplates::cv
geometry: margin=0.5in

title: "Resume"
author: Ariel Mundo Ortiz

jobtitle: "Postdoctoral Fellow"
address: "Département de médecine sociale et préventive and CReSP, Université de Montréal"
fontawesome: yes
email: ariel.mundo.ortiz@umontreal.ca
#github: aimundo
#twitter: aimundortiz
#osf: "Enter 5 digit osf string here"
phone: "+1 438 875 9203"
web: aimundo.rbind.io
updated: yes

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
linkcolor: blue
urlcolor: blue
---

# Education

*University of Arkansas*, PhD. Biomedical Engineering \hfill May 2022

*Universidad Rafael Landivar (Guatemala)*, B.S. Chemical Engineering (_cum laude_) \hfill 2009


# Research Experience

_Postdoctoral Fellow, Département de médecine sociale et préventive et au centre de recherche en santé publique_ (Université de Montréal, Montreal, QC) \hfill June 2023-Present

Working on ongoing projects of public health, disease modelling and infectious diseases in the Nasri Lab.

Worked at the Nasri Lab at the School of Public Health (ESPUM) doing research in infectious disease modelling, collaborated with different groups research groups, and contributed to grant applications from the lab.


_Postdoctoral Fellow, Centre de Recherches Mathématiques_ (Université de Montréal, Montreal, QC) \hfill July 2022-June 2023

Worked at the Nasri Lab at the School of Public Health (ESPUM) doing research in infectious disease modelling, collaborated with different groups research groups, and contributed to grant applications from the lab.

_Postdoctoral Fellow_ (University of Arkansas, Fayetteville, AR) \hfill May 2022-July 2022

Working at the Translational Biophotonics and Imaging Laboratory in de Department of Biomedical Engineering to analyze longitudinal optical and molecular data.

_Graduate Research Assistant_ (University of Arkansas, Fayetteville, AR) \hfill Aug 2017- May 2022

Designed and executed experiments in an animal model of colon cancer using optics and molecular biology to longitudinally quantify changes in perfusion and gene expression in response to therapy. Implemented Statistical semi-parametric models (generalized additive models) to analyze longitudinal data.

# Other Relevant Experience

**Universidad Rafael Landivar**

_Teaching Assistant Professor_  \hfill 2016-2017

- Professor of Chemistry at the Environmental and Agricultural Sciences Department
- Prepared lectures, supervised labs, mentored students, wrote lab manuals

_Adjunct Professor_ \hfill 2013-2017

- Taught Introductory Chemistry in the Engineering, Environmental and Agricultural, and Health Sciences Departments

**Lacteos Balcanicos Glad**

_Assistant Plant Engineer_ \hfill 2012

- In charge of the production of the main product (yogurt, $\approx$ 3000 L per week)

# Publications
## Journal Articles

Molla Jeta, Sekkak Idriss, **Mundo Ortiz Ariel I.**, Moyles Iain, Nasri Bouchra. “Mathematical modeling of mpox: a scoping review”. Submitted to BMC Public Health in December 2022.

**Mundo Ortiz Ariel I.**, Muhammad Abdussaboor, Balza Kerlin, Nelson Christopher E., Muldoon Timothy J. “Longitudinal examination of perfusion and angiogenesis markers in primary colorectal tumors shows distinct signatures for metronomic and maximum-tolerated dose strategies”. Neoplasia (2022). https://doi.org/10.1016/j.neo.2022.100825

**Mundo Ortiz  Ariel I.**, Tipton John R., Muldoon  Timothy J. “Generalized additive models to analyze non-linear trend sin biomedical longitudinal data using R: Beyond repeated measures ANOVA and Linear Mixed Models.” Statistics in Medicine (2022). https://doi.org/10.1002/sim.9505

**Mundo Ortiz  Ariel I.**, Greening  Gage, Fahr  Michael J., Hale  Lawrence N., Bullard  Elizabeth, Rajaram  Narasimhan, and Muldoon Timothy J. “Diffuse reflectance spectroscopy to monitor murine colorectal tumor progression and therapeutic response.” Journal of Biomedical Optics (2020). https://doi.org/10.1117/1.JBO.25.3.035002

Greening Gage, **Mundo Ortiz Ariel I.**,  Rajaram Narasimhan,  Muldoon Timothy  J.  “Sampling  depth  of  a  diffuse  re-flectance spectroscopy probe forin-vivophysiological quantification of murine subcutaneous tumor allografts”.Journal of Biomedical Optics (2018). https://doi.org/10.1117/1.JBO.23.8.085006

## Conference Presentations

**Mundo Ortiz, Ariel I.** "Reproducible papers in the life sciences using R". CANSSI Statistical Software Conference. November 2022. Recording: https://www.youtube.com/watch?v=4yRAR9fS3pg

**Mundo Ortiz, Ariel I.**. "Statistics and Reproducibility in Biomedical Research". 2022 Toronto Workshop on Reproducibility. Toronto, ON. February 2022. Recording: https://www.youtube.com/watch?v=Fvkp20X5xwA

**Mundo Ortiz, Ariel I.**, Muldoon, Timothy J. "Longitudinal optical and molecular quantification provides insight into the effect of different dosing strategies in colorectal cancer". 2022 Biophotonics Congress: Biomedical Optics, Fort Lauderdale, FL, USA, April 2022.

**Mundo Ortiz, Ariel I.** "Statistics and Reproducibility in Biomedical Research: Why we need both". Toronto Workshop on Reproducibility, University of Toronto, February 2022. Recording available [here](https://www.youtube.com/watch?v=Fvkp20X5xwA).

**Mundo Ortiz, Ariel I.** "Using generalized additive models for biomedical longitudinal data. _When linear models don't work_". RMedicine 2021 Conference. Recording: https://tinyurl.com/39epnrp6 Repository (slides and data): https://aimundo.rbind.io/talks/gams-biomedical/

**Mundo Ortiz, Ariel I.**, Abdussaboor Muhammad, and Timothy J. Muldoon. "Optical and molecular longitudinal tracking of primary colorectal murine tumors shows differences in the angiogenic response to maximum-tolerated and metronomic approaches." In Label-free Biomedical Imaging and Sensing (LBIS) 2021, vol. 11655, p. 116551C. _International Society for Optics and Photonics_, 2021. https://doi.org/10.1117/12.2576906

**Mundo Ortiz, Ariel I.**, Elizabeth Bullard, Kyle P. Quinn, and Timothy J. Muldoon. "Optical spectroscopic and imaging biomarkers of ulcerative colitis disease progression and remission (Conference Presentation)." In Multiscale Imaging and Spectroscopy, vol. 11216, p. 1121605. _International Society for Optics and Photonics_, 2020. https://doi.org/10.1117/12.2543369

**Mundo Ortiz, Ariel I.**, Gage J. Greening, and Timothy Muldoon. "Characterization of a multimodal endoscopically deployable veterinary spectroscopy and imaging probe to determine therapeutic response in a murine orthotopic tumor model." In Label-free Biomedical Imaging and Sensing (LBIS) 2019, vol. 10890, p. 108901L. _International Society for Optics and Photonics_, 2019.


# Awards and Recognition

_Fields Institute: Mathematics for Public Health Festival (MfPHFest)_ \hfill October 2022

Received funding to attend the MfPHFest conference and present postdoctoral work done in the field of Statistics. (CAD 1,500)

_Centre de recherches mathématiques (CRM) MfPH-CRM Postdoctoral Fellowship_ \hfill July 2022

Received postdoctoral fellowship for one year to analyze public health and behavioral data (CAD 50,000)

_BME Rising Scholar_ \hfill June 2022

Selected by the committee of the BME Scholars Program at Washington University in St. Louis to receive mentorship about pathways and professional success in academic careers. Award included paid travel, conference attendance and honorarium. 

_Professional Awareness, Advancement, and Development (PADD) Scholar_ \hfill 2020-2021 
 
 Received funding and participated in the PAAD program to supplement my graduate education in persuasive speaking, commercialization, and data science (USD 1,500).
 
 _OMNI Endowed International Scholarship_ \hfill 2020

Granted as a scholar fulfilling the mission of the OMNI Center in Fayetteville (USD 500)

_Fulbright Faculty Development Scholarship_ \hfill 2017-2019

Scholarship covered all costs of my PhD for the first two years. Only two scholarships awarded for that period in the whole country. (USD 78,000)

# Grants

_Canada Institutes of Health Research (CIHR)_ \hfill 2023

Co-investigator in the grant "epidemiological modelling of behavioural impact on mpox mitigation strategies" lead by Prof. Nasri from Université de Montréal.
Involved with the writing of the grant, communicating with team members, performing literature reviews, and grant objective development.
Funding secured: CAD 824,000.
The proposal was in the 50% rank within the competition.
Record of the grant can be found in the  \href{https://webapps.cihr-irsc.gc.ca/decisions/p/project_details.html?applId=481271&lang=en}{CIHR funding decision database}.


_Arkansas Biosciences Institute 2021 seed grant competition _ \hfill 2021

Main author on a proposal co-submitted with Dr. Timothy Muldoon to examine gene expression and optically derived markers in a mouse model of colorectal cancer.
Funding secured: USD 30,000.
The proposal scored in the top 2 of all the individual research projects for the cycle.



