---
output: stevetemplates::statement
geometry: margin=0.5in

title: "Cover Letter"
author: Ariel Mundo

jobtitle: "Graduate Research Assistant"
address: "Department of Biomedical Engineering · University of Arkansas · Fayetteville, AR"
fontawesome: yes
email: aimundo@uark.edu
github: aimundo
# twitter: stevenvmiller
#osf: "Enter 5 digit osf string here"
phone: "+1 479 800 8714"
web: aimundo.rbind.io
updated: yes

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
linkcolor: blue
urlcolor: blue
---


I have spent the last four years of my PhD trying to better understand the changes caused by colon cancer using a primary murine model. However, it has become clear to me that the way we study any disease (cancer, diabetes, obesity, etc.) in preclinical research is limited by two fundamental reasons: 1) we use animal or cellular models that approximate the behavior of a disease in humans, but that have many inherent limitations, and 2) we usually take "snapshots" of how things change over time. 

The first limitation has repeatedly caused a lack of replicability in the clinical setting from promising results seen in traditional model organisms, but despite this the scientific community continues to invest heavily in this type of research. The second limitation is even more baffling to me: why are we so accustomed to see things only "before" and "after"? Diseases are progressive! And yet, we lack fundamental metabolic and cellular information with enough time resolution that enables us to predict not only _how_ things change but also _when_ they change. 

Until we acknowledge the need for longitudinal information in all areas of science, we are condemned to see not only a lack of replicability in results, but a growing disorganized array of information that will not help us to give definite answers to many biological problems (e.g., the Warburg effect in cancer).

My next career choice is not solely focused on discoveries that help tackle the limitations mentioned above, but also in laying the theoretical and practical foundations on _how_ to address these questions systematically in an interdisciplinary manner where novel approaches across Statistics, Biology and Bioinformatics can be leveraged and presented in order to help change what we consider "paradigms" in the scientific community. 

