---
author: Ariel Mundo
return-address: 
   - 1796 E Parkshore Dr.
   - Apt. 4
   - Fayetteville, AR, 72703
address:
  # - "1796 E Parkshore Dr."
  # - "Apt. 4"
  # - "Fayetteville, AR, 72703"
colorlinks: true
inline-links: true
subject: Future Consideration of Employment at RStudio
opening: Dear Hiring Manager at RStudio,
closing: Best regards,
signature: Ariel Mundo
lco: UScommercial9
output: komaletter::komaletter


---

I am currently a Graduate Research Assistant training towards my PhD in Biomedical Engineering at the University of Arkansas. This letter is to be considered in future employment opportunities. Allow me to provide a little context of why I am interested in working at RStudio: All my life, I *hated* Statistics. I suffered enough in College with my Stats classes, and until the first year of my PhD (where I was required to take a Statistics class) I saw Statistics as a necessary evil. All of that changed the day I sat on the computer to try to analyze some data I had been collecting for months (the details of such data are in a paper [**here**](https://www.spiedigitallibrary.org/journals/journal-of-biomedical-optics/volume-25/issue-3/035002/Diffuse-reflectance-spectroscopy-to-monitor-murine-colorectal-tumor-progression-and/10.1117/1.JBO.25.3.035002.full?SSO=1)). 

My desire to learn how to properly analyze this dataset led me to take a class in R. After that, I did not stop and took an advanced computational Statistics class, and read multiple Statistics books. The use of `ggplot2` and the `tidyverse` radically changed the way I viewed data analysis and from the moment I started using them, I became an avid R/ RStudio user. My journey with R led me to write a paper on statistical methods for biomedical data, where I learned to use `Bookdown`, do some coding in $LaTeX$ and to collaborate using GitHub (the pre-print is available [**here**](https://www.biorxiv.org/content/10.1101/2021.06.10.447970v2)). To date, I consider this paper the most fulfilling and challenging experience because it sharpened my writing and coding skills, and made me work hard to make my work reproducible and accessible. I have also started a [**personal website**](http://aimundo.rbind.io/) using `Blogdown` and `Hugo` where I make posts about coding and learning R. 

My main interests are research reproducibility and data visualization. I enjoy solving problems where a good amount of creativity is required, and where I can collaborate and learn from people that have different views that can help make a better end product. I connect with the vision of RStudio of helping people understand and improve the world through data, and I think it is something that is much need in academic research (particularly in biomedical research). Furthermore, I think my unique combination of skills (biomedical sciences research in conjunct with R coding expertise) may be valuable to RStudio.

I would be delighted to work at RStudio once I finish my PhD, and I believe my skills and my proven track on independent learning make me an ideal candidate for the company. I look forward to hearing from you in the near future.
